# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/openjdk:11-jdk
    
version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - restore_cache:
        keys:
        - m2-cache-v0.1
    - run: make build-ci
    - store_test_results:
        path: target/surefire-reports
    - save_cache:
        key: m2-cache-v0.1
        paths:
        - "$HOME/.m2"

  deploy:
    <<: *defaults
    steps:
    - checkout
    - run: make deploy-ci

  release:
    <<: *defaults
    steps:
    - checkout
    - run: make release-ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
