# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/openjdk:10-jdk
    
version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: mvn clean install
            
  deploy:
    <<: *defaults
    steps:
    - checkout
    - run: mvn -s .circleci.settings.xml deploy -Dmaven.test.skip=true
    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
